# server
server:
  port: 5555

#Enable disk space health check.
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# spring
spring:
  application:
    name: zuulserver # Eureka 에 등록할 service logical name
  profiles:
    active: default


# eureka
eureka:
  instance:
    prefer-ip-address: true # service 이름(hostname) 대신 service ip address 등록
  client:
    register-with-eureka: true # eureka 에 service 등록
    fetch-registry: true # eureka service location
    service-url:
      defaultZone: http://localhost:8761/eureka/ # registry 사본을 local 로 가져오기

# zuul
zuul:
  ignored-services: '*' # eureka service id 기반의 모든 경로를 등록에서 제외한다.
  prefix: /api # 접두어
  routes:
    origanizationservice: /organization/**
    licensingservice: /lisensing/**

#  routes: # 수동 맵핑
#    organizationservice: /organization/**
#  ignored-services: # 무시할 service list
#    - organizationservice
