#Enable disk space health check.
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# spring
spring:
  application:
    name: zuulserver # Eureka 에 등록할 service logical name
  profiles:
    active: default


# zuul
zuul:
  ignored-services: '*' # eureka service id 기반의 모든 경로를 등록에서 제외한다.
  prefix: /api # 접두어
  routes:
    origanizationservice: /organization/**
    licensingservice: /licensing/**
    configserver: /configserver/**
  debug:
    request: true

# zuul timeout
hystrix:
  command:
    default: # default 는 모든 서비스에 적용됨 - 특정 서비스에만 적용할 경우 service id 를 넣으면 됨
      execution:
        isolation:
          thread:
            timeoutInMiliseconds: 3000 # 단위 ms

licensingservice:
  ribbon:
    ReadTimeout: 7000 # ribbon timeout 단위 ms