# server
server:
  port: 8080

#Enable disk space health check.
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# spring
spring:
  application:
    name: licensingservice # Spring Cloud Config Client 가 어떤 서비스를 조회할 지 알수 있도록 지정
  profiles:
    active: default # Service 가 실행할 기본 프로파일 지정
  config:
    import: configserver:http://localhost:8888 # Spring Cloud Config 서버 위치 지정


encrypt:
  key: IMSYMMETRIC # study 하는것이므로 대칭키를 일단 환경 설정 파일에 정의

# eureka
eureka:
  instance:
    prefer-ip-address: true # service 이름(hostname) 대신 service ip address 등록
  client:
    register-with-eureka: true # eureka 에 service 등록
    fetch-registry: true # eureka service location
    service-url:
      defaultZone: http://localhost:8761/eureka/ # registry 사본을 local 로 가져오기

